import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Cairo } from 'next/font/google';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Indicator",
  description: "Generated by create next app",
};
const cario = Cairo({
  subsets: ['latin'],
  weight: ['400', '700'], 
});
export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased{cario.className}`}
      >     
        <div className="navbar bg-base-100 shadow-sm">
  <div className="navbar flex justify-between">
    
    <a className="text-4xl font-extrabold">مؤشرات</a>
    <div className="dropdown">
      <div tabIndex="0" role="button" className="btn btn-ghost lg:hidden">
        <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"> <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h8m-8 6h16" /> </svg>
      </div>
      <ul
        tabIndex="0"
        className="menu menu-sm -ms-24 dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow">
        <li><Link href="/">الصفحة الرئيسية</Link></li>
        <li><Link href="/indicator">المؤشرات</Link></li>
        <li><Link href="/previewFile">تحميل وتحليل الملف</Link></li>
      </ul>
    </div>
    
  </div>


  <div className="navbar-center hidden lg:flex">
    <ul className="menu menu-horizontal px-1">
      <li><Link href="/">الصفحة الرئيسية</Link></li>
      <li><Link href="/indicator">المؤشرات</Link></li>
      <li><Link href="/previewFile">تحميل وتحليل الملف</Link></li>
    </ul>
  </div>
  
</div>

      <footer>
        <p className="text-center fixed bottom-0 w-full p-4 bg-base-100">
         &copy; صنع بواسطة :رتَـق ، م. رهف فهد  - 2025  
        </p>
      </footer>
        {children}
      </body>
    </html>
  );
}
